[project]
name = "address-parser"
version = "1.0.0"
description = "A modern web application for parsing addresses from RTF files"

[build]
command = "bash deploy.sh"
output = "dist"

[serve]
command = "python3 -m http.server 8000"
port = 8000
static = true
directory = "dist"

[deploy]
rebuild = true
pre_deploy = "echo 'Preparing for Coolify deployment...'"
post_deploy = "echo 'Coolify deployment complete!'"
script = "deploy.sh"

[files]
include = [
    "address_parser.html",
    "README.md",
    ".gitignore",
    "deploy.sh"
]

exclude = [
    "*.rtf",
    "*.log",
    "*.tmp",
    "dist/"
]

[dev]
watch = ["address_parser.html"]
reload = true
command = "python3 -m http.server 8000" 